### ISSUE TITLE
example to update item's attribute as string

### ISSUE THREAD

**Issue by zxkane** [awslabs/dynein#82]
I can update an existing item to set/add attribute as `boolean` or `number`.

```bash
# working when set the `attr` as boolean or number
dy upd key --set "attr = false"
dy upd key --set "attr = 100"
```
When set an attribute as string, I got below error. No idea how making it work.
```bash
dy upd key --set "attr = 'ssss'"
thread 'main' panicked at 'failed to parse right hand object ''ssss'' into AttributeValue.', src/data.rs:553:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

dy upd key --set "attr = ssss"  
thread 'main' panicked at 'failed to parse right hand object 'ssss' into AttributeValue.', src/data.rs:553:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by StoneDot** [comment]
This issue has been addressed in #132. You can now use both single-quoted strings and double-quoted strings. We have plans to release it in v0.3.0.
